// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq1HbyIfrhtQWNx7hsl5FWqMYNPjGgErY',
    appId: '1:167492820164:web:e2a56df79579cd0fcabd91',
    messagingSenderId: '167492820164',
    projectId: 'men-barde',
    authDomain: 'men-barde.firebaseapp.com',
    storageBucket: 'men-barde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI2EeP554rKZSqYvyjXRNhtVWklgPXk3M',
    appId: '1:167492820164:android:bccff951a544fd2dcabd91',
    messagingSenderId: '167492820164',
    projectId: 'men-barde',
    storageBucket: 'men-barde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXoL8Kz-7_aLZIUtKQ_K22R2CCBAEg2is',
    appId: '1:167492820164:ios:a058da9e68dac141cabd91',
    messagingSenderId: '167492820164',
    projectId: 'men-barde',
    storageBucket: 'men-barde.appspot.com',
    iosClientId: '167492820164-2djkj06ggeubh5m82t9sqh7poo1a0l6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.menBarde',
  );
}
